theme: jekyll-theme-minimal
title: Aditya Jain's Homepage
# description: adityajain7@outlook.com | (402) 517-5659 
# description: "[adityajain7@outlook.com](mailto:adityajain7@outlook.com) | (402) 517-5659"
description: '<a href="mailto:adityajain7@outlook.com">adityajain7@outlook.com</a> | 402-517-5659'
# Setup
url:                 http://adityajain70.github.io/

# Add these lines:
logo: /images/pic3.jpeg  # Path to your photo
show_downloads: false
github:
  is_project_page: false
  is_user_page: false
