theme: jekyll-theme-minimal
title: Aditya Jain's Homepage
description: ajain9@unl.edu | (402) 517-5659 | adityajain7@outlook.com
# Setup
url:                 http://adityajain70.github.io/

# Add these lines:
logo: /images/pic3.jpeg  # Path to your photo
show_downloads: false
github:
  is_project_page: false
  is_user_page: false
